### ISSUE TITLE
Healthkit bg import

### ISSUE THREAD

**Issue by francesc0-cgm** [JohanDegraeve/iosxdripreader#1]
Hi Johan, I wonder if you could add import of bg reading in healthkit so it could be possible to use it for offline looping using xdrip rig.

**Comment by JohanDegraeve** [comment]
Hi,

I didn't understand your question. What is healthkit ? what is "offline looping" ?

John

**Comment by francesc0-cgm** [comment]
Sorry Johan...I mean Health from Apple to provide bg readings to https://github.com/LoopKit/Loop

**Comment by JohanDegraeve** [comment]
This looks rather easy yes.
I would need to write a native extension because the flex environment that I use doesn't support this. 

I'm adding here some sample just for myself to find back just in case
https://code.tutsplus.com/tutorials/getting-started-with-healthkit-part-1--cms-24477


I'll try it out.

**Comment by francesc0-cgm** [comment]
Any news John? I saw you are trying to work on stability too

**Comment by francesc0-cgm** [comment]
And reconnecting issue

**Comment by JohanDegraeve** [comment]
Indeed I just finished and succeeded in reconnecting after losing the bluetooth connection (device out and back in range). It's not so easy due to this adobe framework I use. The solution was to send a remote notification every 5 minutes, this brings the app back active and gives me the opportunity to scan for the device and connect if it is in range.
Also the upload to NightScout is now working (also using the remote notification trigger).

So I'm quite happy now.

And yes I started looking at the healthkit, I should have time now to continue with it.

So if I will understand, the goal is that by app would write bgreadings  into the healthkit store.
Then another app (yours ?) would read that date from the healthkit ?
I read that apps are not allowed to read from the healthkit if they are in the background. Would that be an issue ?

**Comment by francesc0-cgm** [comment]
Great so if your app has solved that problem we can use it to loop off line with xdrip. It is a great news! Loop is capable to read from healthkit without any problem. But if you are not in US and you are not using a G5 you have to use xdrip plus to upload data on dexcom server then use dexcom follow on the iphone to get bgs on healthkit. From there loop reads the bg and decides to give or get out insulin. Of course this means you have to be online on the uploading side and on loop-iphone side. If your app is capable to write data there you can keep xdrip rig in the pocket and iphone will take data on your app, will write them on healthkit and loop will take them from there and this will happen without any need for internet connection. Let me know your future steps...if you need a tester i'm here

**Comment by ps2** [comment]
I think this is great! Reading the comments above, it looks like there might be an impression the Loop reads BG from HK that was put in by external sources.  It doesn't actually do that right now.  It uses other frameworks to snoop on BLE events, and stores data into HK itself. 

With some work, though, Loop could be updated to read BG data stored in HK by external programs and make predictions based on it.

**Comment by francesc0-cgm** [comment]
Sorry @Ps2 i thought it could read data from there. Might it be possible to include John app as a framework in loop as you did for riley framework?

**Comment by JohanDegraeve** [comment]
Could you send me your UDID's of your iOS device(s) ? So i can compile a version that you can install (via iTunes).

**Comment by francesc0-cgm** [comment]
Check FB i sent you a PM


In data 7 Gennaio 2017 9:17:04 AM Johan Degraeve <notifications@github.com> 
ha scritto:

**Comment by JohanDegraeve** [comment]
Hi Francesco, 

the releases tab has now version 0.0.21 which can be installed on both of your devices.

regards,

Johan

**Comment by JohanDegraeve** [comment]
I added healthkit storage but I'm not able to compile. Seems related to my usage of flex framework.
I'll give it lower priority

**Comment by francesc0-cgm** [comment]
Hi Johan. I tested the app and seems more stable than before.
It lacks of bt reconnection but seems usable.


Inviato da iPad

**Comment by JohanDegraeve** [comment]
I know reconnect still not ok. I'm still trying to improve that

**Comment by JohanDegraeve** [comment]
no progress
