### ISSUE TITLE
xDrip G4 w/ Wixel

### ISSUE THREAD

**Issue by squallyfungus32** [JohanDegraeve/iosxdripreader#14]
I've tried version 1.0.3 and 0.52 and haven't been able to get Nightscout to update with any data. In both versions the calibration button never appears, so I'm not sure it's receiving data. Bluetooth is OK.

- The app appears to connect to Nightscout OK
- The Wixel connects quickly (in .52 the Bluetooth icon is green, in 1.0.3 the status is connected)
- I've tried selecting G4 as the transmitter and have entered the ID of the actual transmitter or left it as 0000 (though I don't see why i'd need that? The Wixel has that value hardcoded).
- I've started and stopped the sensor, restarted the app, used airplane mode. I've also tried changing the start time of the sensor in case that's the problem.

Oh, for the record, I also had trouble setting the high value in mmol format. I had to change the unit to mgdl, enter a number, then switch back to mmol.

I've used a developer ID to resign the apps, so testing different versions isn't a problem.

Thanks

**Comment by JohanDegraeve** [comment]
Hi,

- depending on the firmware you have installed, you can update the transmitter id via the app, that's why you can set the transmitter id in the app (although it's not mandatory if it's already hardcoded)
- some users have issues with xdrip from http://xdripkit.co.uk/
I don't know if that's the case for you. My app doesn't seem to work with it, don't know exactly why

can you install this firmware ?

https://raw.githubusercontent.com/jstevensog/wixel-sdk/master/apps/xBridge2/xBridge2.wxl

Please also send me detailed tracing, in the settings, you can enable
then test for a longer period, then send me the logs.

I'll check about the high value in mmol

thanks a lot,

Johan

**Comment by squallyfungus32** [comment]
Sorry this took a while, I ran into some issues getting xBridge2.wxl to work on my Mac, but sorted it out on my SurfaceBook. 

My xDrip is an old OG one, built with a HM-10, [using this guide](https://github.com/StephenBlackWasAlreadyTaken/xDrip/blob/master/hardware_setup.md) without he voltage measurement mod. 

I've updated the firmware of the HM-10 module with V550 and then installed xBridge2.wxl. I sent you a log by email last night. Since playing with it further this morning, it looks like the new software isn't communicating with the transmitter (and/or is ignoring the Transmitter ID setting) as I was able to replicate the issue on xDrip+ on Android. xDrip+ previously worked with on the old xDrip firmware.

I guess i'll go over xBridge2 again and see if there's anything I missed.

**Comment by JohanDegraeve** [comment]
Yes I'v received a trace.
Can you install 1.0.4 ? i've added some additional info in the logs like device type, status of the sensor, status of the calibrations.
Also enable the tracing before you start actually testing.
In the logs there seems to be very little information, indeed some bluetoothcommunication but with empty data packets

**Comment by dghinet** [comment]
Hello! Is this application compatible with G4 transmitter? Does anybody tested it?
I am currently using XDRIP paired with G4 and uploader app installed on Android.
Thank you in advance!
Dan

**Comment by JohanDegraeve** [comment]
@squallyfungus32 do you still have a problem ?
