### ISSUE TITLE
Alarms are not cancelled

### ISSUE THREAD

**Issue by Mondelman** [JohanDegraeve/iosxdripreader#17]
Whenever I mute my phone, or I need to delay a bit the calibration, alarm is popping up every minute, even when I select snoozing it for a few minutes.
Is there any way to list "active" alarms so we can select which one has to be cancelled or active?

**Comment by JohanDegraeve** [comment]
No there is No such list.

But snoozing doesn’t seem to work. Can you send me detailed tracing ?
Enable the tracing and when this happens send it to me

Op ma 9 okt. 2017 om 10:59 schreef Mondelman <notifications@github.com>

**Comment by JohanDegraeve** [comment]
If an alarm is popping up every minute, then maybe you have set "repeat" to "yes" in the alert type ?
can you check that ?
This is an iOS feature : if the notification is fired, and as long as you don't handle the notification (ie don't open it or swipe it away), it will re-fire every minute.

In the logs that you've sent I see that the default snooze period for phone muted alert is 5 minutes. So that means if you snooze the alert from your phone home screen, the default snooze period is 5 minutes, which is rather low, it will probably fire again in 5, maximum 10 minutes.
Can you check that also ?

I see the same snooze period (5 minutes) for missed reading alert, seems rather low.

I'm  not saying there's nothing wrong with the app, because I also have the impression during the night that especially the low alert doesn't snooze correctly. 

![img-0808](https://user-images.githubusercontent.com/13840461/31410798-c89271dc-ae0f-11e7-993c-665754f5caae.PNG)

**Comment by Mondelman** [comment]
Hi Johan,

Many thanks for your comments.
I tested your suggestions and it works perfectly.
My only concern is especially with “muted phone” alarm. When it fires up, there’s no way to cancel it. It becomes especially painful when you mute your phone accidentally and this alarm is beeping forever. No way to shut it off.

Thanks for commenting.

Miguel Ten

De: Johan Degraeve
Enviado: martes, 10 de octubre de 2017 23:08
Para: JohanDegraeve/iosxdripreader
CC: Mondelman; Author
Asunto: Re: [JohanDegraeve/iosxdripreader] Alarms are not cancelled (#17)

If an alarm is popping up every minute, then maybe you have set "repeat" to "yes" in the alert type ?
can you check that ?
This is an iOS feature : if the notification is fired, and as long as you don't handle the notification (ie don't open it or swipe it away), it will re-fire every minute.
In the logs that you've sent I see that the default snooze period for phone muted alert is 5 minutes. So that means if you snooze the alert from your phone home screen, the default snooze period is 5 minutes, which is rather low, it will probably fire again in 5, maximum 10 minutes.
Can you check that also ?
I see the same snooze period (5 minutes) for missed reading alert, seems rather low.
I'm not saying there's nothing wrong with the app, because I also have the impression during the night that especially the low alert doesn't snooze correctly.

**Comment by JohanDegraeve** [comment]
You should be able to snooze it. But if your default snooze is 5 minutes it
Will repeat after 5 minutes

Op wo 11 okt. 2017 om 09:04 schreef Mondelman <notifications@github.com>

**Comment by Mondelman** [comment]
Yes, you're right. But I can't cancel it, even when the event that fired up the alarm is not exisiting any more...
Thanks!

Miguel

**Comment by JohanDegraeve** [comment]
You Can simply swipe awat the notification. If the alarm is not applicable
anymore the notification Will not reappear. If you dont do anything and in
5 minutes the alarm is not applicable anymore it Then also the notification
Will be remover . Assuming you have your transmitter around. Because it is
the Bluetooth activity that wakes up the app and allows the app to vzrify
the status of alarms and notifications. Except for the Missed reading alert
which is a future plannen notification

Op wo 11 okt. 2017 om 09:37 schreef Mondelman <notifications@github.com>

**Comment by Mondelman** [comment]
OK, thanks Johan.

**Comment by JohanDegraeve** [comment]
I think I found an error in the snoozing, I also experienced several times during the night that alarms keep repeating while I snoozed, but I was never sure if it was because it was halfly dreaming or it it was really an error. Not it happened while I was awake and found something .. fix in upcoming release

**Comment by Mondelman** [comment]
Cool!

Miguel Ten
+34 676 35 38 37

**Comment by JohanDegraeve** [comment]
see release 1.1.2
