### ISSUE TITLE
Would like to contribute - are there any tests?

### ISSUE THREAD

**Issue by Stray** [JohanDegraeve/iosxdripreader#2]
Great work. I'd love to be useful, but I can't see a test suite - am I missing it?

**Comment by JohanDegraeve** [comment]
Hi Stray,

testing is possible off course but the build it you need an iOS developer account and some licenses for packages that I baught ([airnativeextensions.com](https://airnativeextensions.com/)). 
If you give me your UDID and can give you an IPA that you can install on your UDID. (you can send it to johan.degraeve@gmail.com)

At the moment it works for G4 but it's in functionality far away from Android version.
I'm  now on G5 however and at the moment I'm trying to get the connection running.

What are you skills ? a possible contribution : 
The app receives a notification every 5 minutes. This happens in the minute after generation of the bgreading. 
At initial start up, the app registers at [quickblox](https://quickblox.com/). It also assigns a "tag", being "one", "two", "three" , "four" or "five". It indicates the minute in which it wants to receive a notification. As soon as the first bgreading is received, this tag will be updated (the app sends update to quickblox), depending on the minute in which the bgreading was received. Example, if the bgreading is received at 16:02:15, 16:07:15, 16:12:15 ... then it will subscribe to tag "three".
At 16:03:15, the app will receive a notification. The purpose off that notification is to trigger a background upload to Nightscout.

Triggering of those notifications happens through another app running on a spare iphone @ my home.
Not very nice, so this could be improved.
Another advantage of this notification is that it allows the app to verify the bluetooth connection. If it's not connected it will start scanning.
And I think I will need it also for the G5, apparently the G5 disconnects after having send a bgreading, and it advertises as soon as a new reading is available. The notification should be send a few seconds in advance, so it should be more accurate.

That's just a high level explanation, I need to try now to make g5 work

**Comment by Stray** [comment]
Thanks Johan,

I've got an OS Dev account and I've been looking at the ANEs you mention as an alternative/adjunct to the Feathers UI components for mobile dev.

I'm an experienced AS3/Air developer (was one of the core contributors to Robotlegs and I've written books for O'Reilly) but I'm new to mobile - though I am now doing mobile for my main projects. 

I've been active in open-source previously but quiet for a few years as I was very ill at diagnosis and it has taken a while to get to grips with all this diabetes nonsense.

I'd be happy to take this notifications task on (with more detail from you), but I'm used to TDD and having a test-suite to verify that nothing is broken as changes are made, before I request a pull - are there tests that you just haven't uploaded, or are there none? In which case it would probably be more useful for me to start by creating tests, as that makes it easier for other developers to contribute? 

Thanks,

Stray

**Comment by JohanDegraeve** [comment]
Hi Stray,

good to hear you're better now.

ok you seem to have 10 times more knowledge than me then :)

I don't have a test suite actually. Not used to that. 

Maybe before jumping into a lot of work, we need to see whether this app is really going to be used by many others.
One important factor is that it will probably be impossible to release this to the app store. Apple wants to see if an app is useful. I'm not going to send them an xDrip or G5.
Moreover I would need to refer to Dexcom. I don't think Dexcom would like to see this in an official app released in the appstore.

For now there's about 10 people who have send me their UDID and that have an IPA to test.

Also I need to guarantee some stability in the Bluetooth connection. This seems to be quite difficult due to the use of the Adobe Air platform.
iOS puts an app in suspended mode if the bluetooth connection is lost. Normally if the device is back in range, iOS would "wake-up" the app, but that's not happening with my app.
A workaround is this remote notification which actually does wake up the app, for 30 seconds and allows to verify the Bluetooth connection. THe remote notification is meant (by iOS) to do down and uploads actually.
But it's not very clean. It depends on this remote notification, Apple does not guarantee that remote notifications are actually sent. 

First step for me is to get the G5 working, because more and more people are going from G4 to G5 (me too).
Once that's progressing I'll make a more detailed description of this notification mechanism.

But off course if you think you can start working on other stuff, don't hesitate. 
To setup the environment you'll need some additional classes with secret keys, for instance the airnative extension license keys.
Let me know how you think you want to proceed.

regards,

Johan

**Comment by JohanDegraeve** [comment]
Hi Stray,

I made good progress with G5.
Could you send me your UDID (johan.degraeve@gmail.com) ? I'll send you an install later this week, then you can try it out,

regards,

Johan

**Comment by Nargly** [comment]
Johan,
I just sent you my UDID, would love to help test the latest builds you have.  Didn't see them here if they are available could you direct me?
Thanks!

**Comment by JohanDegraeve** [comment]
Hi Nargly,

I'll prepare an install that supports your UDID later these evening.

Actually I try to test as much as I can before releasing anything. What I
release is intended to be used. Off course bugs are still possible, but I'm
using it know actually.


regards,

Johan
