### ISSUE TITLE
1.1.18 - will it be available for group 4?

### ISSUE THREAD

**Issue by Tashmand** [JohanDegraeve/iosxdripreader#22]
Hi
Apologies for the dumb question, but it looks like 1.1.18 is only available for group 5? Is this correct or am i missing something?
Thanks so much for everything you do!
Tash

**Comment by miguelkennedy** [comment]
This is correct... sometimes it takes a day or two for all groups to be available... Tomorrow all groups should be ready to download...

**Comment by Nargly** [comment]
Dumb question, what are the groups?

**Comment by miguelkennedy** [comment]
When you send your UDID to @JohanDegraeve in order to have the IPA signed and ready to be install in your iPhone you are assigned to a group (you're also notified which group you belong to). From there onwards you can only install the IPA corresponding to your group, the other IPAs won't work on your device... If by any chance you are the one signing the IPA, then you won't belong to any group and you can download and sign the iosxdripreader.ipa (with no group associated).

**Comment by JohanDegraeve** [comment]
group3 is added just now, group2 and 4 will follow soon
