### ISSUE TITLE
using rest api to upload bg value to openaps during bt tethering

### ISSUE THREAD

**Issue by francesc0-cgm** [JohanDegraeve/iosxdripreader#3]
Could you try to implement a rest api upload to a local bt address when iPhone is tethered via bt to an openaps rig to use xdripaps with?

**Comment by JohanDegraeve** [comment]
Hi 
I don't really understand your question.
But adding a call to an additional rest api should be feasible.
Do you have documentation on that API ?

Johan

**Comment by francesc0-cgm** [comment]
Of course sorry. This is the same thing done using a special version of 
loop https://github.com/thebookins/xDripAPS


In data 20 Aprile 2017 23:56:25 Johan Degraeve <notifications@github.com> 
ha scritto:

**Comment by JohanDegraeve** [comment]
So in fact it's like as if the app would be calling a second nightscout url ? is it the same api (json format etc..).
I could make a test version so that you could enter the full url being http://<api_secret>@<rig_ip_address>:5000/api/v1/

One thing to note is that it would probably not work without Internet Connection.
iOS doesn't allow to make http calls if an app (iosxdripreader) is running in the background.
The way to force this is by sending a notification. I have a spare iphone here at home which sends a remote notification to every iosxdripreader-user every 5 minutes, which awakens the app and gives  it 30 seconds to make http calls. (this happens in between 30 - 90 seconds after the reading).
This notification off course will never arrive on the device if there's no Internet

**Comment by francesc0-cgm** [comment]
I think that version of loop could work offline without any problem...


In data 21 Aprile 2017 00:27:28 Johan Degraeve <notifications@github.com> 
ha scritto:

**Comment by JohanDegraeve** [comment]
This is interesting to read 
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW56
This explains "fetching data", but it applies also to "posting data" which is what happens when posting data to Nightscout.
What the documentation says "the system gives time to apps when there are good opportunities to do so". I tested this  and actually the more the user uses the app, the more ios will give the app the opportunity to fetch (or post) data. But an app that is newly installed, and typicall xdrip is normally never open, it will actually never get the opportunity to fetch (or post data).
I tested keeping the app open for 24 hours, a day later, my app got this opportunity every 10 minutes. But sill not synchronized with the transmitter, so there were delays of up to 15 minutes.
One would think that by [allowing background fetch](https://www.google.be/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjVq-eA_7TTAhVNKVAKHVjUBrMQjRwIBw&url=http%3A%2F%2Fwww.imore.com%2Fhow-to-manage-background-app-refresh-iphone-ipad&psig=AFQjCNEuBqeoWxzjH9FhbIAy2yUWbpGKcQ&ust=1492844962419524) , that the app would be allowed to fetch/post data at any time. But the answer is no. It's as described above.

The solution is [remote notifications](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW57).

I really think that uploading via bluetooth tethering will be exactly the same behaviour. 
But we can try off course. 
First of all I'll change the code so that you add a http (not https) url and give the full domain name, port number ...
Then you can test with the app in the foreground (in fact if the app is in the foreground the upload happens immediately).

do I have your UDID ?

**Comment by francesc0-cgm** [comment]
You already have mine Johan (I'm alessandro)


In data 21 Aprile 2017 09:12:40 Johan Degraeve <notifications@github.com> 
ha scritto:

**Comment by JohanDegraeve** [comment]
ah ok :)
I wasn't sure actually
I Will send you an update today or tomorrow

**Comment by JohanDegraeve** [comment]
ah ok :)
I wasn't sure actually
I Will send you an update today or tomorrow

**Comment by francesc0-cgm** [comment]
Thank you


In data 21 Aprile 2017 09:25:13 Johan Degraeve <notifications@github.com> 
ha scritto:

**Comment by JohanDegraeve** [comment]
Hi Alessandro,

here a new version https://1drv.ms/u/s!AoD_n2ttq1dEkf0mwXkmQ3H784grvg
In the nightscout url, use http://<rig_ip_address>:5000
ie without the api secret, this you put as before in the separate setting, also don't add the api/v1, the code is doing that

And keep the app in the foreground.
If you get this working, then I'll try to add the upload also when the app is in the background

regards,

Johan

**Comment by francesc0-cgm** [comment]
Api secret isn't needed?


In data 21 Aprile 2017 5:07:30 PM Johan Degraeve <notifications@github.com> 
ha scritto:

**Comment by JohanDegraeve** [comment]
Yes but in my app it's a seperate setting
so you don't need (should not) add it in the url setting
