### ISSUE TITLE
Road map?

### ISSUE THREAD

**Issue by Nargly** [JohanDegraeve/iosxdripreader#4]
Just wanted to know if there is a road map for development?  I'm particularly interested in graphing and history for reads.  I miss that in the Android xDrip and the iOS Dexcom app.

**Comment by JohanDegraeve** [comment]
currently I'm busy with alarms, I think this will finish around end of June or maybe later.
I plan to have a graph on the first screen but for me this is not top priority. I also don't know yet how good this will be, graphing is something new for me. I think it will be very basic.

I think it's better if you use NightScout, the readings can be uploaded to NightScout. If I want to see a graph I use the Safari browser with the Nightscout url.

**Comment by Nargly** [comment]
Johan, Thanks for the update.  Alarms are very important.  I prefer autonomy in the app, so the graph is high on my personal list, and I appreciate your consideration of it.  Get job so far, looking forward to future updates.

**Comment by JohanDegraeve** [comment]
alarms are progressing, there's a version 33 available that supports low alarms, I'm busy adding more.

The next step will indeed be the graph

**Comment by Nargly** [comment]
Johan, curiosity question:  Is this app 64-bit so it will work on iOS 11 which only supports 64-bit and not 32-bit?  Wanted to know before I jumped into the iOS 11 beta. 
The alarms look good so far.  Keep up the great work!

**Comment by JohanDegraeve** [comment]
Hi,

thanks for the positive feedback.

It should be 64-bit. It's already two years that Apple only accepts 64-bit in the app store and I have another app already there. I'm using the same environment and settings.

On the other hand, since I'm using  the Apache Flex framework, it happened before that after an upgrade (I think it was 7 to 8) my app gave a black screen. It took 6 months before it got solved.

But it would certainly be a good test :)

regards,

Johan

**Comment by Nargly** [comment]
Any plan to do an "urgent low"?  :)

**Comment by JohanDegraeve** [comment]
I've been thinking of adding a "very low" and "very high" yes.
I probably will soon.

**Comment by Nargly** [comment]
CHART!  Woot!  Looks great.  Thanks!  :)
