### ISSUE TITLE
Graph missing

### ISSUE THREAD

**Issue by CrushingT1D** [JohanDegraeve/iosxdripreader#5]
I am not getting any graph visualization on v0.0.41 using mgdl and a range low 55, high 140 and Transmitter type G5. It is pushing the values into Nightscout fine and shows the change over time, how long ago, BG value and the arrow fine.

**Comment by xpucuto** [comment]
Jim , there is no graph visualization in the app itself . You can only see the current bg , the delta and the arrow .

**Comment by JohanDegraeve** [comment]
Hi,

indeed graph is not yet available, this is lowest priority for me.
The Nightscout upload is working fine indeed today but this week there were quite some issues, a lot can go wrong with Nightscout upload so please don't count on it. I'm using it because I see my values while typing here :)

what can go wrong
- a spare iphone at home is sending notifications for every user, every 5 minutes. Electricity failure (I had it this week), WiFi failure, phone or application crashing ... 
- the notification is sent to Quickblox, a free service. In the last 6 months it happened two times that this services was not working anymore for several hours
- Quickblox sends the notification to Apple. Apple doesn't guarantee to forward the notification to your device, although I don't think there's problems there.
- Your device , iOS, tries to minimize battery usage. If upload to Nightscout takes too much time for many times, iOS may not forward the notification to the app, simply to save battery consumption.
- Once the app has received the notification, it has maximum 30 seconds to do the upload. In the next release I have set a timer of 3 seconds. Usually upload happens in less than a second. But if your site is down/slow, it may take longer (max 3 seconds with next release coming up), resulting again in iOS deciding to restrict the notifications in the future

I'm still trying to improve the reliability of NightScout upload. 

A graph is maybe for the coming months.

regards,

Johan

**Comment by CrushingT1D** [comment]
No worries, i thought i saw in one of the releases that you made some improvements to the graph.
Thanks for the other tips. 
Great progress since I last looked!
